{% set name = "ndbc-api" %}
{% set version = "0.25.06.06.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndbc_api-{{ version }}.tar.gz
  sha256: 6d348bbf3d109a99b27117486dbb622adef6dc0d6e32dcc2e71e6a1e9112837b


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<3.13
    - pip
    - poetry
  run:
    - python >=3.7,<3.13
    - requests
    - pandas
    - beautifulsoup4
    - urllib3
    - xarray
    - scipy
    - h5netcdf

test:
  imports:
    - ndbc_api

about:
  home: https://github.com/cdjellen/ndbc-api
  summary: A Python API for the National Data Buoy Center.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CDJellen
